<?php

namespace Database\Seeders;

use App\Models\Formation;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class FormationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $formations = [
            // ===== LANGUES =====
            ['titre' => ['fr' => 'Français A1-A2', 'en' => 'French A1-A2'], 'slug' => 'francais-a1-a2', 'description_courte' => ['fr' => 'Cours de français débutant', 'en' => 'Beginner French'], 'description_complete' => ['fr' => 'Apprentissage des bases : grammaire, vocabulaire et communication simple.', 'en' => 'Learning basics: grammar, vocabulary and simple communication.'], 'prix' => 150000.00, 'duree' => '3 mois', 'category_id' => 6, 'is_featured' => true],
            ['titre' => ['fr' => 'Français B1-B2', 'en' => 'French B1-B2'], 'slug' => 'francais-b1-b2', 'description_courte' => ['fr' => 'Intermédiaire-avancé', 'en' => 'Intermediate-advanced'], 'description_complete' => ['fr' => 'Maîtrise des structures complexes et communication professionnelle.', 'en' => 'Complex structures and professional communication.'], 'prix' => 180000.00, 'duree' => '4 mois', 'category_id' => 6],
            ['titre' => ['fr' => 'Français C1-C2', 'en' => 'French C1-C2'], 'slug' => 'francais-c1-c2', 'description_courte' => ['fr' => 'Cours avancé', 'en' => 'Advanced course'], 'description_complete' => ['fr' => 'Maîtrise parfaite de la langue et nuances professionnelles.', 'en' => 'Perfect command of the language and professional nuances.'], 'prix' => 200000.00, 'duree' => '5 mois', 'category_id' => 6],
            ['titre' => ['fr' => 'Anglais A1-A2', 'en' => 'English A1-A2'], 'slug' => 'anglais-a1-a2', 'description_courte' => ['fr' => 'Anglais débutant', 'en' => 'Beginner English'], 'description_complete' => ['fr' => 'Bases de la grammaire, vocabulaire essentiel et communication basique.', 'en' => 'Grammar basics, essential vocabulary and basic communication.'], 'prix' => 150000.00, 'duree' => '3 mois', 'category_id' => 7, 'is_featured' => true],
            ['titre' => ['fr' => 'Anglais B1-B2', 'en' => 'English B1-B2'], 'slug' => 'anglais-b1-b2', 'description_courte' => ['fr' => 'Anglais intermédiaire', 'en' => 'Intermediate English'], 'description_complete' => ['fr' => 'Fluidité conversationnelle et vocabulaire professionnel.', 'en' => 'Conversational fluency and professional vocabulary.'], 'prix' => 180000.00, 'duree' => '4 mois', 'category_id' => 7],
            ['titre' => ['fr' => 'TOEFL/TOEIC/IELTS', 'en' => 'Test Preparation'], 'slug' => 'preparation-tests', 'description_courte' => ['fr' => 'Tests internationaux', 'en' => 'International tests'], 'description_complete' => ['fr' => 'Stratégies d\'examen et pratique intensive pour les tests reconnus.', 'en' => 'Exam strategies and intensive practice for recognized tests.'], 'prix' => 220000.00, 'duree' => '3 mois', 'category_id' => 7, 'is_featured' => true],
            ['titre' => ['fr' => 'Espagnol A1-B1', 'en' => 'Spanish A1-B1'], 'slug' => 'espagnol-a1-b1', 'description_courte' => ['fr' => 'Castillan moderne', 'en' => 'Modern Castilian'], 'description_complete' => ['fr' => 'De débutant à intermédiaire avec focus sur communication quotidienne.', 'en' => 'From beginner to intermediate with focus on daily communication.'], 'prix' => 160000.00, 'duree' => '4 mois', 'category_id' => 8],
            ['titre' => ['fr' => 'Allemand A1-B1', 'en' => 'German A1-B1'], 'slug' => 'allemand-a1-b1', 'description_courte' => ['fr' => 'Allemand débutant', 'en' => 'Beginner German'], 'description_complete' => ['fr' => 'Grammaire structurée et communication professionnelle.', 'en' => 'Structured grammar and professional communication.'], 'prix' => 160000.00, 'duree' => '4 mois', 'category_id' => 9],
            ['titre' => ['fr' => 'Italien A1-B1', 'en' => 'Italian A1-B1'], 'slug' => 'italien-a1-b1', 'description_courte' => ['fr' => 'Italien', 'en' => 'Italian'], 'description_complete' => ['fr' => 'Culture et communication orale au cœur de la formation.', 'en' => 'Culture and oral communication at the heart of training.'], 'prix' => 160000.00, 'duree' => '4 mois', 'category_id' => 10],
            ['titre' => ['fr' => 'Chinois A1-B1', 'en' => 'Chinese A1-B1'], 'slug' => 'chinois-a1-b1', 'description_courte' => ['fr' => 'Mandarin', 'en' => 'Mandarin'], 'description_complete' => ['fr' => 'Caractères, prononciation et communication interculturelle.', 'en' => 'Characters, pronunciation and intercultural communication.'], 'prix' => 180000.00, 'duree' => '5 mois', 'category_id' => 11],

            // ===== PARAMÉDICALE =====
            ['titre' => ['fr' => 'Vendeur en Pharmacie', 'en' => 'Pharmacy Salesperson'], 'slug' => 'vendeur-pharmacie', 'description_courte' => ['fr' => 'Diplôme National', 'en' => 'National Diploma'], 'description_complete' => ['fr' => 'Accueil client, conseil thérapeutique et gestion de stock pharmaceutique. Certifié par le Ministère.', 'en' => 'Customer service, therapeutic advice and pharmaceutical management. Ministry-certified.'], 'prix' => 350000.00, 'duree' => '12 mois', 'niveau_entree' => 'Bac', 'category_id' => 12, 'is_featured' => true],
            ['titre' => ['fr' => 'Délégué Médical', 'en' => 'Medical Delegate'], 'slug' => 'delegue-medical', 'description_courte' => ['fr' => 'Représentant médical', 'en' => 'Medical Representative'], 'description_complete' => ['fr' => 'Connaissance des produits pharmaceutiques et relations professionnelles avec les professionnels de santé.', 'en' => 'Pharmaceutical knowledge and professional relationships with healthcare professionals.'], 'prix' => 300000.00, 'duree' => '9 mois', 'category_id' => 13],
            ['titre' => ['fr' => 'Auxiliaire de Vie', 'en' => 'Care Giver'], 'slug' => 'auxiliaire-vie', 'description_courte' => ['fr' => 'Diplôme National', 'en' => 'National Diploma'], 'description_complete' => ['fr' => 'Services aux personnes : aide à la vie quotidienne et support émotionnel.', 'en' => 'Personal care: daily life assistance and emotional support.'], 'prix' => 280000.00, 'duree' => '12 mois', 'niveau_entree' => 'Bac', 'category_id' => 14, 'is_featured' => true],
            ['titre' => ['fr' => 'Maintenance Biomédicale', 'en' => 'Biomedical Maintenance'], 'slug' => 'maintenance-biomedical', 'description_courte' => ['fr' => 'Diplôme National', 'en' => 'National Diploma'], 'description_complete' => ['fr' => 'Entretien, réparation et dépannage des équipements médicaux.', 'en' => 'Maintenance, repair and troubleshooting of medical equipment.'], 'prix' => 320000.00, 'duree' => '12 mois', 'niveau_entree' => 'Bac sci', 'category_id' => 15],
            ['titre' => ['fr' => 'Infirmier Hygiène & Santé', 'en' => 'Nurse Public Health'], 'slug' => 'infirmier-hygiene', 'description_courte' => ['fr' => 'Santé publique', 'en' => 'Public Health'], 'description_complete' => ['fr' => 'Santé publique et prévention. Promotion de la santé et gestion d\'urgences.', 'en' => 'Public health and prevention. Health promotion and emergency management.'], 'prix' => 250000.00, 'duree' => '6 mois', 'category_id' => 14],
            ['titre' => ['fr' => 'Technician Laboratoire', 'en' => 'Lab Technician'], 'slug' => 'technician-laboratoire', 'description_courte' => ['fr' => 'Analyses médicales', 'en' => 'Medical Analysis'], 'description_complete' => ['fr' => 'Analyses médicales : prélèvement, analyse et interprétation des résultats.', 'en' => 'Medical analysis: sampling, analysis and result interpretation.'], 'prix' => 260000.00, 'duree' => '8 mois', 'category_id' => 14],

            // ===== HUMANITAIRE =====
            ['titre' => ['fr' => 'Bases de l\'Humanitaire', 'en' => 'Humanitarian Fundamentals'], 'slug' => 'bases-humanitaire', 'description_courte' => ['fr' => 'Principes humanitaires', 'en' => 'Humanitarian Principles'], 'description_complete' => ['fr' => 'Valeurs et principes de l\'action humanitaire. Histoire, droits et responsabilités.', 'en' => 'Values and principles of humanitarian action. History, rights and responsibilities.'], 'prix' => 150000.00, 'duree' => '2 mois', 'category_id' => 16],
            ['titre' => ['fr' => 'Épidémiologie & Urgences', 'en' => 'Epidemiology'], 'slug' => 'epidemiologie-urgences', 'description_courte' => ['fr' => 'Épidémiologie de terrain', 'en' => 'Field Epidemiology'], 'description_complete' => ['fr' => 'Investigation épidémiologique, surveillance et réponse aux crises sanitaires.', 'en' => 'Epidemiological investigation, surveillance and health crisis response.'], 'prix' => 200000.00, 'duree' => '3 mois', 'category_id' => 17, 'is_featured' => true],
            ['titre' => ['fr' => 'Logistique Humanitaire', 'en' => 'Humanitarian Logistics'], 'slug' => 'logistique-humanitaire', 'description_courte' => ['fr' => 'Supply chain', 'en' => 'Supply Chain'], 'description_complete' => ['fr' => 'Gestion de la supply chain en contexte humanitaire. Approvisionnement et distribution.', 'en' => 'Supply chain management in humanitarian context. Supply and distribution.'], 'prix' => 170000.00, 'duree' => '2.5 mois', 'category_id' => 18],
            ['titre' => ['fr' => 'Gestion de Projet Humanitaire', 'en' => 'Humanitarian Project Mgmt'], 'slug' => 'gestion-projet-humanitaire', 'description_courte' => ['fr' => 'Gestion de projets', 'en' => 'Project Management'], 'description_complete' => ['fr' => 'Conception, planification et suivi de projets humanitaires. Ressources et reporting.', 'en' => 'Design, planning and monitoring of humanitarian projects. Resources and reporting.'], 'prix' => 190000.00, 'duree' => '3 mois', 'category_id' => 16],
            ['titre' => ['fr' => 'Santé Mentale & Psychosocial', 'en' => 'Mental Health Support'], 'slug' => 'sante-mentale-psychosocial', 'description_courte' => ['fr' => 'Soutien psychosocial', 'en' => 'Psychosocial Support'], 'description_complete' => ['fr' => 'Soutien psychologique en crise. Premiers secours psychologiques et gestion du traumatisme.', 'en' => 'Psychological support in crisis. Psychological first aid and trauma management.'], 'prix' => 180000.00, 'duree' => '2.5 mois', 'category_id' => 19, 'is_featured' => true],
            ['titre' => ['fr' => 'WASH Humanitaire', 'en' => 'WaSH'], 'slug' => 'wash-humanitaire', 'description_courte' => ['fr' => 'Eau, hygiène, assainissement', 'en' => 'Water, Hygiene, Sanitation'], 'description_complete' => ['fr' => 'Eau, hygiène et assainissement en contexte humanitaire. Standards WASH et prévention.', 'en' => 'Water, hygiene and sanitation in humanitarian context. WASH standards and prevention.'], 'prix' => 160000.00, 'duree' => '2 mois', 'category_id' => 16],
            ['titre' => ['fr' => 'Education en Urgence', 'en' => 'Education in Emergencies'], 'slug' => 'education-urgence', 'description_courte' => ['fr' => 'Éducation d\'urgence', 'en' => 'Emergency Education'], 'description_complete' => ['fr' => 'Maintien de l\'éducation en crises. Pédagogie d\'urgence et protection de l\'enfant.', 'en' => 'Maintaining education in crises. Emergency pedagogy and child protection.'], 'prix' => 170000.00, 'duree' => '2.5 mois', 'category_id' => 16],
            ['titre' => ['fr' => 'Nutrition Humanitaire', 'en' => 'Nutrition'], 'slug' => 'nutrition-humanitaire', 'description_courte' => ['fr' => 'Nutrition en contexte', 'en' => 'Nutrition in Context'], 'description_complete' => ['fr' => 'Évaluation nutritionnelle et programmes d\'alimentation. Dépistage malnutrition.', 'en' => 'Nutritional assessment and feeding programs. Malnutrition screening.'], 'prix' => 175000.00, 'duree' => '2.5 mois', 'category_id' => 16],

            // ===== NUMÉRIQUE EN SANTÉ =====
            ['titre' => ['fr' => 'Data Analyst en Santé', 'en' => 'Health Data Analyst'], 'slug' => 'data-analyst-sante', 'description_courte' => ['fr' => 'Analyse de données', 'en' => 'Data Analysis'], 'description_complete' => ['fr' => 'Excel, SPSS, DHIS2, Kobo, ODK et visualisation. Formation appliquée.', 'en' => 'Excel, SPSS, DHIS2, Kobo, ODK and visualization. Applied training.'], 'prix' => 240000.00, 'duree' => '4 mois', 'category_id' => 4, 'is_featured' => true],
            ['titre' => ['fr' => 'Cartographie SIG', 'en' => 'GIS Mapping'], 'slug' => 'cartographie-sante', 'description_courte' => ['fr' => 'SIG en santé', 'en' => 'GIS in Health'], 'description_complete' => ['fr' => 'QGIS et ArcGIS pour la cartographie sanitaire. Systèmes d\'Information Géographique.', 'en' => 'QGIS and ArcGIS for health mapping. Geographic Information Systems.'], 'prix' => 200000.00, 'duree' => '3 mois', 'category_id' => 4],
            ['titre' => ['fr' => 'IA pour Santé', 'en' => 'AI for Health'], 'slug' => 'ia-sante', 'description_courte' => ['fr' => 'Intelligence Artificielle', 'en' => 'Artificial Intelligence'], 'description_complete' => ['fr' => 'Applications de l\'IA en santé clinique. Machine learning pour diagnostic et prédiction.', 'en' => 'AI in clinical health. Machine learning for diagnosis and prediction.'], 'prix' => 260000.00, 'duree' => '4 mois', 'category_id' => 4],
            ['titre' => ['fr' => 'Python pour Santé Publique', 'en' => 'Python for Public Health'], 'slug' => 'python-sante', 'description_courte' => ['fr' => 'Python appliqué', 'en' => 'Applied Python'], 'description_complete' => ['fr' => 'Programmation Python appliquée à la santé publique. Analyse statistique et automatisation.', 'en' => 'Python programming in public health. Statistical analysis and automation.'], 'prix' => 220000.00, 'duree' => '3.5 mois', 'category_id' => 4],

            // ===== MANAGEMENT & RECHERCHE =====
            ['titre' => ['fr' => 'Protocole de Recherche', 'en' => 'Research Protocol'], 'slug' => 'protocole-recherche', 'description_courte' => ['fr' => 'Méthodologie', 'en' => 'Methodology'], 'description_complete' => ['fr' => 'Méthodologie de recherche en santé. Formulation de questions et protocoles scientifiques.', 'en' => 'Health research methodology. Research questions and scientific protocols.'], 'prix' => 210000.00, 'duree' => '3 mois', 'category_id' => 5, 'is_featured' => true],
            ['titre' => ['fr' => 'Enquête CAP', 'en' => 'KAP Survey'], 'slug' => 'enquete-cap', 'description_courte' => ['fr' => 'CAP Survey', 'en' => 'KAP Survey'], 'description_complete' => ['fr' => 'Conduite d\'enquêtes CAP. Analyse de comportements et interventions basées sur les données.', 'en' => 'KAP surveys. Behavior analysis and data-driven interventions.'], 'prix' => 190000.00, 'duree' => '2.5 mois', 'category_id' => 5],
            ['titre' => ['fr' => 'Enquête Épidémiologique', 'en' => 'Epi Survey'], 'slug' => 'enquete-epidemiologique', 'description_courte' => ['fr' => 'Investigation épid.', 'en' => 'Epi Investigation'], 'description_complete' => ['fr' => 'Planification et exécution d\'investigations épidémiologiques. Surveillance des maladies.', 'en' => 'Epidemiological investigations. Disease surveillance and rapid response.'], 'prix' => 200000.00, 'duree' => '3 mois', 'category_id' => 5],
            ['titre' => ['fr' => 'Évaluation Projet', 'en' => 'Project Evaluation'], 'slug' => 'evaluation-projet-sante', 'description_courte' => ['fr' => 'Évaluation', 'en' => 'Evaluation'], 'description_complete' => ['fr' => 'Méthodes d\'évaluation de projets. Indicateurs, données et rapportage.', 'en' => 'Project evaluation methods. Indicators, data collection and reporting.'], 'prix' => 210000.00, 'duree' => '3 mois', 'category_id' => 5],
            ['titre' => ['fr' => 'EIE en Santé', 'en' => 'Environmental Impact'], 'slug' => 'eie-sante', 'description_courte' => ['fr' => 'EIE', 'en' => 'EIE'], 'description_complete' => ['fr' => 'Analyse environnementale en santé. Impacts et mesures de prévention.', 'en' => 'Environmental analysis in health. Impacts and prevention measures.'], 'prix' => 190000.00, 'duree' => '2.5 mois', 'category_id' => 5],
            ['titre' => ['fr' => 'Planification Sanitaire', 'en' => 'Health Planning'], 'slug' => 'planification-sanitaire', 'description_courte' => ['fr' => 'Planification', 'en' => 'Planning'], 'description_complete' => ['fr' => 'Planification stratégique en santé. Plans d\'action et allocation de ressources.', 'en' => 'Strategic health planning. Action plans and resource allocation.'], 'prix' => 200000.00, 'duree' => '3 mois', 'category_id' => 5],
            ['titre' => ['fr' => 'Évaluation Système Santé', 'en' => 'Health System Eval'], 'slug' => 'evaluation-systeme-sante', 'description_courte' => ['fr' => 'Système de santé', 'en' => 'Health System'], 'description_complete' => ['fr' => 'Analyse complète des systèmes de santé. Performance, équité et efficacité.', 'en' => 'Health system analysis. Performance, equity and effectiveness.'], 'prix' => 210000.00, 'duree' => '3 mois', 'category_id' => 5],
        ];

        foreach ($formations as $formation) {
            Formation::create($formation);
        }
    }
}

