<?php

namespace Database\Seeders;

use App\Models\Formation;
use Illuminate\Database\Seeder;

class FormationSeeder extends Seeder
{
    public function run(): void
    {
        $formations = [
            // ===== CATÉGORIE 1: LES LANGUES =====
            ['titre' => ['fr' => 'Français (A1-B2)', 'en' => 'French (A1-B2)'], 'slug' => 'francais', 'description_courte' => ['fr' => 'Formation complète en français', 'en' => 'Complete French training'], 'description_complete' => ['fr' => 'Apprenez le français du niveau débutant à intermédiaire avancé. Programme adaptatif qui vous permet de progresser à votre rythme, de la communication quotidienne à la maîtrise professionnelle. Cours en présentiel et en ligne disponibles.', 'en' => 'Learn French from beginner to upper-intermediate level. Adaptive program that allows you to progress at your own pace, from daily communication to professional mastery. Face-to-face and online courses available.'], 'debouches' => ['fr' => 'Administration, enseignement, traduction, emplois francophones', 'en' => 'Administration, teaching, translation, French-speaking jobs'], 'prerequis' => ['fr' => 'Aucun prérequis', 'en' => 'No prerequisites'], 'prix' => null, 'duree' => null, 'category_id' => 1, 'is_featured' => true],
            
            ['titre' => ['fr' => 'Anglais (A1-B2)', 'en' => 'English (A1-B2)'], 'slug' => 'anglais', 'description_courte' => ['fr' => 'Formation complète en anglais', 'en' => 'Complete English training'], 'description_complete' => ['fr' => 'Maîtrisez l\'anglais du niveau débutant à intermédiaire avancé. Vocabulaire professionnel, communication d\'affaires, compréhension orale et écrite. Préparation solide pour le monde du travail international.', 'en' => 'Master English from beginner to upper-intermediate level. Professional vocabulary, business communication, oral and written comprehension. Solid preparation for the international workplace.'], 'debouches' => ['fr' => 'Multinationales, ONG, tourisme, commerce international', 'en' => 'Multinationals, NGOs, tourism, international trade'], 'prerequis' => ['fr' => 'Aucun prérequis', 'en' => 'No prerequisites'], 'prix' => null, 'duree' => null, 'category_id' => 1, 'is_featured' => true],
            
            ['titre' => ['fr' => 'Préparation TOEFL/TOEIC/IELTS', 'en' => 'TOEFL/TOEIC/IELTS Preparation'], 'slug' => 'toefl-toeic-ielts', 'description_courte' => ['fr' => 'Certifications internationales d\'anglais', 'en' => 'International English certifications'], 'description_complete' => ['fr' => 'Préparez-vous efficacement aux tests internationaux d\'anglais (TOEFL, TOEIC, IELTS). Stratégies d\'examen, tests blancs, coaching personnalisé et techniques pour maximiser votre score. Formateurs expérimentés et supports officiels.', 'en' => 'Prepare effectively for international English tests (TOEFL, TOEIC, IELTS). Exam strategies, mock tests, personalized coaching and techniques to maximize your score. Experienced trainers and official materials.'], 'debouches' => ['fr' => 'Études à l\'étranger, immigration, emplois internationaux', 'en' => 'Study abroad, immigration, international jobs'], 'prerequis' => ['fr' => 'Niveau B1 minimum recommandé', 'en' => 'B1 level minimum recommended'], 'prix' => null, 'duree' => null, 'category_id' => 1, 'is_featured' => true],
            
            ['titre' => ['fr' => 'Espagnol (A1-B2)', 'en' => 'Spanish (A1-B2)'], 'slug' => 'espagnol', 'description_courte' => ['fr' => 'Formation complète en espagnol', 'en' => 'Complete Spanish training'], 'description_complete' => ['fr' => 'Apprenez l\'espagnol du niveau débutant à intermédiaire avancé. Deuxième langue la plus parlée au monde, l\'espagnol ouvre de nombreuses portes professionnelles. Formation progressive et interactive.', 'en' => 'Learn Spanish from beginner to upper-intermediate level. The second most spoken language in the world, Spanish opens many professional doors. Progressive and interactive training.'], 'debouches' => ['fr' => 'Commerce international, tourisme, traduction', 'en' => 'International trade, tourism, translation'], 'prerequis' => ['fr' => 'Aucun prérequis', 'en' => 'No prerequisites'], 'prix' => null, 'duree' => null, 'category_id' => 1],
            
            ['titre' => ['fr' => 'Allemand (A1-B2)', 'en' => 'German (A1-B2)'], 'slug' => 'allemand', 'description_courte' => ['fr' => 'Formation complète en allemand', 'en' => 'Complete German training'], 'description_complete' => ['fr' => 'Maîtrisez l\'allemand pour vos études ou votre carrière. Formation structurée du niveau débutant à intermédiaire avancé. Idéal pour les opportunités en Allemagne, Autriche et Suisse.', 'en' => 'Master German for your studies or career. Structured training from beginner to upper-intermediate level. Ideal for opportunities in Germany, Austria and Switzerland.'], 'debouches' => ['fr' => 'Études en Allemagne, entreprises allemandes, ingénierie', 'en' => 'Studies in Germany, German companies, engineering'], 'prerequis' => ['fr' => 'Aucun prérequis', 'en' => 'No prerequisites'], 'prix' => null, 'duree' => null, 'category_id' => 1],
            
            ['titre' => ['fr' => 'Italien (A1-B2)', 'en' => 'Italian (A1-B2)'], 'slug' => 'italien', 'description_courte' => ['fr' => 'Formation complète en italien', 'en' => 'Complete Italian training'], 'description_complete' => ['fr' => 'Découvrez la langue et la culture italiennes. Formation complète du niveau débutant à intermédiaire avancé. Parfait pour le tourisme, la mode et les affaires.', 'en' => 'Discover the Italian language and culture. Complete training from beginner to upper-intermediate level. Perfect for tourism, fashion and business.'], 'debouches' => ['fr' => 'Tourisme, mode, luxe, commerce', 'en' => 'Tourism, fashion, luxury, trade'], 'prerequis' => ['fr' => 'Aucun prérequis', 'en' => 'No prerequisites'], 'prix' => null, 'duree' => null, 'category_id' => 1],
            
            ['titre' => ['fr' => 'Chinois Mandarin (A1-B2)', 'en' => 'Mandarin Chinese (A1-B2)'], 'slug' => 'chinois', 'description_courte' => ['fr' => 'Formation complète en mandarin', 'en' => 'Complete Mandarin training'], 'description_complete' => ['fr' => 'Maîtrisez le mandarin pour le commerce international. Apprentissage complet : caractères, prononciation, tons et culture chinoise. La langue de l\'avenir économique mondial.', 'en' => 'Master Mandarin for international trade. Complete learning: characters, pronunciation, tones and Chinese culture. The language of the global economic future.'], 'debouches' => ['fr' => 'Commerce avec la Chine, import-export, interprétariat', 'en' => 'Trade with China, import-export, interpreting'], 'prerequis' => ['fr' => 'Aucun prérequis', 'en' => 'No prerequisites'], 'prix' => null, 'duree' => null, 'category_id' => 1],

            // ===== CATÉGORIE 2: PARAMÉDICAL =====
            ['titre' => ['fr' => 'Vendeur en Pharmacie', 'en' => 'Pharmacy Salesperson'], 'slug' => 'vendeur-pharmacie', 'description_courte' => ['fr' => 'Diplôme National d\'État - 12 mois', 'en' => 'National State Diploma - 12 months'], 'description_complete' => ['fr' => 'Formation diplômante reconnue par l\'État. Devenez expert en conseil pharmaceutique, gestion des stocks et service client en officine. Stage pratique inclus.', 'en' => 'State-recognized diploma training. Become an expert in pharmaceutical advice, stock management and customer service in pharmacies. Practical internship included.'], 'debouches' => ['fr' => 'Pharmacies, dépôts pharmaceutiques, parapharmacies', 'en' => 'Pharmacies, pharmaceutical depots, parapharmacies'], 'prerequis' => ['fr' => 'Baccalauréat', 'en' => 'Baccalaureate'], 'prix' => 350000, 'duree' => '12 mois', 'category_id' => 2, 'is_featured' => true],
            ['titre' => ['fr' => 'Délégué Médical', 'en' => 'Medical Delegate'], 'slug' => 'delegue-medical', 'description_courte' => ['fr' => 'Diplôme National d\'État', 'en' => 'National State Diploma'], 'description_complete' => ['fr' => 'Devenez le lien entre les laboratoires pharmaceutiques et les professionnels de santé. Formation en pharmacologie, techniques de vente médicale et communication professionnelle.', 'en' => 'Become the link between pharmaceutical laboratories and healthcare professionals. Training in pharmacology, medical sales techniques and professional communication.'], 'debouches' => ['fr' => 'Laboratoires pharmaceutiques, visiteur médical', 'en' => 'Pharmaceutical laboratories, medical representative'], 'prerequis' => ['fr' => 'Bac scientifique ou santé', 'en' => 'Science or health baccalaureate'], 'prix' => 300000, 'duree' => '9-12 mois', 'category_id' => 2],
            ['titre' => ['fr' => 'Auxiliaire de Vie', 'en' => 'Care Giver'], 'slug' => 'auxiliaire-vie', 'description_courte' => ['fr' => 'Diplôme National d\'État - 12 mois', 'en' => 'National State Diploma - 12 months'], 'description_complete' => ['fr' => 'Formez-vous à l\'accompagnement des personnes âgées et handicapées. Soins d\'hygiène, aide à la mobilité, soutien psychologique et premiers secours.', 'en' => 'Train to support the elderly and disabled. Hygiene care, mobility assistance, psychological support and first aid.'], 'debouches' => ['fr' => 'EHPAD, services à domicile, hôpitaux', 'en' => 'Nursing homes, home services, hospitals'], 'prerequis' => ['fr' => 'BEPC/CAP minimum', 'en' => 'BEPC/CAP minimum'], 'prix' => 280000, 'duree' => '12 mois', 'category_id' => 2, 'is_featured' => true],
            ['titre' => ['fr' => 'Maintenance Biomédicale', 'en' => 'Biomedical Maintenance'], 'slug' => 'maintenance-biomedicale', 'description_courte' => ['fr' => 'Diplôme National d\'État - 12 mois', 'en' => 'National State Diploma - 12 months'], 'description_complete' => ['fr' => 'Expertise technique en maintenance des équipements médicaux. Installation, réparation et entretien des appareils biomédicaux (échographes, respirateurs, etc.).', 'en' => 'Technical expertise in medical equipment maintenance. Installation, repair and maintenance of biomedical devices (ultrasound, ventilators, etc.).'], 'debouches' => ['fr' => 'Services biomédicaux hospitaliers, fournisseurs d\'équipements', 'en' => 'Hospital biomedical services, equipment suppliers'], 'prerequis' => ['fr' => 'Bac technique (F2/F3/C/D)', 'en' => 'Technical baccalaureate'], 'prix' => 320000, 'duree' => '12 mois', 'category_id' => 2],

            // ===== CATÉGORIE 3: HUMANITAIRE =====
            ['titre' => ['fr' => 'Bases de l\'Humanitaire', 'en' => 'Fundamentals of Humanitarian'], 'slug' => 'bases-humanitaire', 'description_courte' => ['fr' => 'Certificat de compétences - En ligne', 'en' => 'Skills Certificate - Online'], 'description_complete' => ['fr' => 'Introduction complète aux principes humanitaires et au fonctionnement des ONG. Idéal pour débuter une carrière dans le secteur humanitaire.', 'en' => 'Complete introduction to humanitarian principles and NGO operations. Ideal to start a career in the humanitarian sector.'], 'debouches' => ['fr' => 'ONG nationales et internationales', 'en' => 'National and international NGOs'], 'prerequis' => ['fr' => 'Baccalauréat', 'en' => 'Baccalaureate'], 'prix' => 150000, 'duree' => '2 mois', 'category_id' => 3],
            ['titre' => ['fr' => 'Épidémiologie de Terrain', 'en' => 'Field Epidemiology'], 'slug' => 'epidemiologie-terrain', 'description_courte' => ['fr' => 'Certificat - Urgences sanitaires', 'en' => 'Certificate - Health emergencies'], 'description_complete' => ['fr' => 'Formation spécialisée en investigation épidémiologique et gestion des urgences sanitaires. Surveillance, détection et riposte aux épidémies.', 'en' => 'Specialized training in epidemiological investigation and health emergency management. Surveillance, detection and epidemic response.'], 'debouches' => ['fr' => 'OMS, ONG santé, ministères', 'en' => 'WHO, health NGOs, ministries'], 'prerequis' => ['fr' => 'Formation en santé', 'en' => 'Health background'], 'prix' => 200000, 'duree' => '3 mois', 'category_id' => 3, 'is_featured' => true],
            ['titre' => ['fr' => 'Logistique Humanitaire', 'en' => 'Humanitarian Logistics'], 'slug' => 'logistique-humanitaire', 'description_courte' => ['fr' => 'Certificat de compétences - En ligne', 'en' => 'Skills Certificate - Online'], 'description_complete' => ['fr' => 'Maîtrisez la gestion logistique en contexte humanitaire. Supply chain, gestion de flotte, approvisionnement et distribution d\'aide d\'urgence.', 'en' => 'Master logistics management in humanitarian context. Supply chain, fleet management, procurement and emergency aid distribution.'], 'debouches' => ['fr' => 'Logisticien ONG, gestionnaire de stocks', 'en' => 'NGO logistician, warehouse manager'], 'prerequis' => ['fr' => 'Bac +2 ou expérience', 'en' => 'Associate degree or experience'], 'prix' => 170000, 'duree' => '2-3 mois', 'category_id' => 3],
            ['titre' => ['fr' => 'Gestion de Projets Humanitaires', 'en' => 'Humanitarian Project Management'], 'slug' => 'gestion-projets-humanitaires', 'description_courte' => ['fr' => 'Certificat de compétences - En ligne', 'en' => 'Skills Certificate - Online'], 'description_complete' => ['fr' => 'Cycle complet de gestion de projets humanitaires : conception, budgétisation, mise en œuvre, suivi-évaluation et rapportage aux bailleurs.', 'en' => 'Complete humanitarian project management cycle: design, budgeting, implementation, monitoring-evaluation and donor reporting.'], 'debouches' => ['fr' => 'Chef de projet, coordinateur ONG', 'en' => 'Project manager, NGO coordinator'], 'prerequis' => ['fr' => 'Licence minimum', 'en' => 'Bachelor minimum'], 'prix' => 190000, 'duree' => '3 mois', 'category_id' => 3, 'is_featured' => true],
            ['titre' => ['fr' => 'WASH Humanitaire', 'en' => 'WaSH in Humanitarian Context'], 'slug' => 'wash-humanitaire', 'description_courte' => ['fr' => 'Eau, Hygiène, Assainissement', 'en' => 'Water, Sanitation, Hygiene'], 'description_complete' => ['fr' => 'Techniques de potabilisation, construction de latrines d\'urgence et promotion de l\'hygiène en contexte humanitaire.', 'en' => 'Water purification techniques, emergency latrine construction and hygiene promotion in humanitarian context.'], 'debouches' => ['fr' => 'Technicien WASH, promoteur hygiène', 'en' => 'WASH technician, hygiene promoter'], 'prerequis' => ['fr' => 'Bac technique ou santé', 'en' => 'Technical or health bac'], 'prix' => 160000, 'duree' => '2 mois', 'category_id' => 3],
            ['titre' => ['fr' => 'Nutrition Humanitaire', 'en' => 'Nutrition in Humanitarian Context'], 'slug' => 'nutrition-humanitaire', 'description_courte' => ['fr' => 'Certificat de compétences - En ligne', 'en' => 'Skills Certificate - Online'], 'description_complete' => ['fr' => 'Dépistage et prise en charge de la malnutrition aiguë. Programmes d\'alimentation thérapeutique et prévention nutritionnelle.', 'en' => 'Screening and management of acute malnutrition. Therapeutic feeding programs and nutritional prevention.'], 'debouches' => ['fr' => 'Nutritionniste projet, assistant nutrition', 'en' => 'Project nutritionist, nutrition assistant'], 'prerequis' => ['fr' => 'Formation santé/nutrition', 'en' => 'Health/nutrition background'], 'prix' => 175000, 'duree' => '2-3 mois', 'category_id' => 3],

            // ===== CATÉGORIE 4: NUMÉRIQUE EN SANTÉ =====
            ['titre' => ['fr' => 'Data Analyst en Santé', 'en' => 'Health Data Analyst'], 'slug' => 'data-analyst-sante', 'description_courte' => ['fr' => 'Diplôme National - 12 mois', 'en' => 'National Diploma - 12 months'], 'description_complete' => ['fr' => 'Formation complète en analyse de données sanitaires. Maîtrisez Excel, SPSS, DHIS2, Kobo Collect, ODK, EpiInfo, R, Python et PowerBI pour transformer les données en décisions.', 'en' => 'Complete training in health data analysis. Master Excel, SPSS, DHIS2, Kobo Collect, ODK, EpiInfo, R, Python and PowerBI to transform data into decisions.'], 'debouches' => ['fr' => 'Data manager, statisticien santé, chargé M&E', 'en' => 'Data manager, health statistician, M&E officer'], 'prerequis' => ['fr' => 'Bac scientifique ou économique', 'en' => 'Science or economics bac'], 'prix' => 350000, 'duree' => '12 mois', 'category_id' => 4, 'is_featured' => true],
            ['titre' => ['fr' => 'Cartographie SIG en Santé', 'en' => 'GIS Health Mapping'], 'slug' => 'cartographie-sig-sante', 'description_courte' => ['fr' => 'Certificat - QGIS, ArcGIS', 'en' => 'Certificate - QGIS, ArcGIS'], 'description_complete' => ['fr' => 'Utilisez les systèmes d\'information géographique pour la santé publique. Cartographie des épidémies, planification sanitaire et analyse spatiale avec QGIS et ArcGIS.', 'en' => 'Use geographic information systems for public health. Epidemic mapping, health planning and spatial analysis with QGIS and ArcGIS.'], 'debouches' => ['fr' => 'Cartographe santé, analyste spatial', 'en' => 'Health cartographer, spatial analyst'], 'prerequis' => ['fr' => 'Aisance informatique', 'en' => 'Computer literacy'], 'prix' => 200000, 'duree' => '3 mois', 'category_id' => 4],
            ['titre' => ['fr' => 'IA pour Professionnels de Santé', 'en' => 'AI for Health Professionals'], 'slug' => 'ia-sante-cliniciens', 'description_courte' => ['fr' => 'Intelligence Artificielle appliquée', 'en' => 'Applied Artificial Intelligence'], 'description_complete' => ['fr' => 'Découvrez les applications de l\'IA en santé clinique et publique. Machine learning, diagnostic assisté et prédiction épidémiologique.', 'en' => 'Discover AI applications in clinical and public health. Machine learning, assisted diagnosis and epidemiological prediction.'], 'debouches' => ['fr' => 'Consultant e-santé, data scientist santé', 'en' => 'e-health consultant, health data scientist'], 'prerequis' => ['fr' => 'Formation santé ou informatique', 'en' => 'Health or IT background'], 'prix' => 260000, 'duree' => '4 mois', 'category_id' => 4],

            // ===== CATÉGORIE 5: MANAGEMENT & RECHERCHE =====
            ['titre' => ['fr' => 'Protocole de Recherche en Santé', 'en' => 'Health Research Protocol'], 'slug' => 'protocole-recherche', 'description_courte' => ['fr' => 'Certificat - Méthodologie', 'en' => 'Certificate - Methodology'], 'description_complete' => ['fr' => 'Apprenez à concevoir un protocole de recherche scientifique. Question de recherche, revue de littérature, méthodologie, éthique et rédaction académique.', 'en' => 'Learn to design a scientific research protocol. Research question, literature review, methodology, ethics and academic writing.'], 'debouches' => ['fr' => 'Chercheur, assistant de recherche, doctorant', 'en' => 'Researcher, research assistant, PhD student'], 'prerequis' => ['fr' => 'Licence/Master', 'en' => 'Bachelor/Master'], 'prix' => 210000, 'duree' => '3 mois', 'category_id' => 5, 'is_featured' => true],
            ['titre' => ['fr' => 'Enquête CAP', 'en' => 'KAP Survey'], 'slug' => 'enquete-cap', 'description_courte' => ['fr' => 'Connaissances, Attitudes, Pratiques', 'en' => 'Knowledge, Attitudes, Practices'], 'description_complete' => ['fr' => 'Maîtrisez la conception et la conduite d\'enquêtes CAP. Questionnaires, échantillonnage, collecte de données et analyse comportementale.', 'en' => 'Master the design and conduct of KAP surveys. Questionnaires, sampling, data collection and behavioral analysis.'], 'debouches' => ['fr' => 'Chargé d\'études, consultant santé communautaire', 'en' => 'Research officer, community health consultant'], 'prerequis' => ['fr' => 'Bac +2 minimum', 'en' => 'Associate degree minimum'], 'prix' => 190000, 'duree' => '2-3 mois', 'category_id' => 5],
            ['titre' => ['fr' => 'Suivi-Évaluation', 'en' => 'Monitoring & Evaluation'], 'slug' => 'suivi-evaluation', 'description_courte' => ['fr' => 'M&E et Redevabilité', 'en' => 'M&E and Accountability'], 'description_complete' => ['fr' => 'Formation complète en suivi-évaluation de projets. Indicateurs, collecte de données, analyse de performance et rapportage aux bailleurs.', 'en' => 'Complete training in project monitoring and evaluation. Indicators, data collection, performance analysis and donor reporting.'], 'debouches' => ['fr' => 'Responsable S&E, auditeur de projets', 'en' => 'M&E manager, project auditor'], 'prerequis' => ['fr' => 'Expérience en gestion de projet', 'en' => 'Project management experience'], 'prix' => 200000, 'duree' => '3 mois', 'category_id' => 5],
            ['titre' => ['fr' => 'Évaluation Système de Santé', 'en' => 'Health System Evaluation'], 'slug' => 'evaluation-systeme-sante', 'description_courte' => ['fr' => 'Certificat de compétences', 'en' => 'Skills Certificate'], 'description_complete' => ['fr' => 'Apprenez à évaluer les systèmes de santé. Performance, équité, efficacité et qualité des services de santé.', 'en' => 'Learn to evaluate health systems. Performance, equity, efficiency and quality of health services.'], 'debouches' => ['fr' => 'Consultant santé, évaluateur de programmes', 'en' => 'Health consultant, program evaluator'], 'prerequis' => ['fr' => 'Formation en santé publique', 'en' => 'Public health background'], 'prix' => 210000, 'duree' => '3 mois', 'category_id' => 5],
        ];

        foreach ($formations as $formation) {
            Formation::create($formation);
        }
    }
}
